//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class COMP229S17S2Entities : DbContext
{
    public COMP229S17S2Entities()
        : base("name=COMP229S17S2Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ingredient> ingredients { get; set; }
    public virtual DbSet<recipe> recipes { get; set; }
    public virtual DbSet<recipeingredient> recipeingredients { get; set; }
}
